p8105_hw1_zx2482
================

``` r
library(moderndive)
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(ggplot2)
```

# Problem 1

``` r
# Load the data
data("early_january_weather")
```

``` r
# Learn the data
variable.names(early_january_weather)
```

    ##  [1] "origin"     "year"       "month"      "day"        "hour"      
    ##  [6] "temp"       "dewp"       "humid"      "wind_dir"   "wind_speed"
    ## [11] "wind_gust"  "precip"     "pressure"   "visib"      "time_hour"

``` r
ncol(early_january_weather)
```

    ## [1] 15

``` r
nrow(early_january_weather)
```

    ## [1] 358

``` r
mean(early_january_weather$"temp")
```

    ## [1] 39.58212

- This dataset consists hourly meterological data for LGA, JFK and EWR
  for the month of January 2013.
- The variable names are as follows:
  “origin”,“year”,“month”,“day”,“hour”,“temp”,“dewp”,“humid”,“wind_dir”,“wind_speed”,“wind_gust”,“precip”,“pressure”,“visib”,“time_hour”
- The size of the dataset is 15 (# of columns) \* 358 (# of rows)
- The mean temperature is 39.58 F

``` r
# Plot
ggplot(early_january_weather, aes (x =time_hour,y = temp, color = humid))+
  geom_point()
```

![](p8105_hw1_zx2482_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

The scatterplot shows the variability of temperatures from January 1st
to 15th at three major airports in the New York area. The fluctuations
on the graph indicate that the temperature rises and falls throughout
the day. Overall, this chart shows a slightly upward trend, implying the
temperature might have increased during January 1-15.The humidity
throughout the month is primarily between 40-80%, but from approximately
January 12th to 14th, the humidity is noticeably higher than usual,
reaching 90-100%.

``` r
# Save the plot
ggsave("scatterplot1.png")
```

    ## Saving 7 x 5 in image

# Problem 2

``` r
# Create the data frame
prob2_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low", "low", "mid", "mid", "mid", "high", "high", "high", "high"))
  )
```

``` r
# Take mean of each variable
mean(pull(prob2_df, samp))
```

    ## [1] 0.1971392

``` r
mean(pull(prob2_df, samp_gt_0))
```

    ## [1] 0.5

``` r
mean(pull(prob2_df, char_vec))
```

    ## Warning in mean.default(pull(prob2_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(prob2_df, factor_vec))
```

    ## Warning in mean.default(pull(prob2_df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

The means of `samp` and `samp_gt_0` can be taken, because `samp` is
numeric and `samp_gt_0` is logical. The means of `char_vec` and
`factor_vec` cannot be taken since they are not numeric or logical.
